language: dart

dart:
  - stable
  - dev

script:
  - pub run dart_dev format --check
  - pub run dart_dev analyze
  - pub run dependency_validator -i coverage,dartdoc,dart_style
  - (cd test_fixtures/valid && pub get)
  - pub run dart_dev test

cache:
 directories:
   - $HOME/.pub-cache
