language: dart

dart:
  - 1.24.3
  - dev

script:
  - dartanalyzer .
  - pub run dart_style:format -l 120 -n .
  - pub run dependency_validator -i build_runner,build_test,coverage,dartdoc,dart_style,_foo,foo,_bar,bar,foo1,foo_foo
  - ./tool/test.sh

cache:
 directories:
   - $HOME/.pub-cache
