language: dart

stages:
  - analyze
  - format
  - test

jobs:
  include:
    - stage: analyze
      dart: [2.2.0, stable, dev]
      script:
        - dartanalyzer .
        - pub run dependency_validator -i _foo,foo,_bar,bar,foo1,foo_foo
    - stage: format
      dart: stable
      script: dartfmt -l 120 -n --set-exit-if-changed .
    - stage: test
      dart: [2.2.0, stable, dev]
      script: pub run test

cache:
 directories:
   - $HOME/.pub-cache
