name: common_binaries
version: 0.0.0
private: true

environment:
  sdk: '>=1.24.2 <3.0.0'

dev_dependencies:
  build_runner: ">=0.6.0+1 <2.0.0"
  build_test: ">=0.9.0 <2.0.0"
  build_vm_compilers: any
  build_web_compilers: ">=0.2.0 <2.0.0"
  built_value_generator: ">=5.1.3 <7.0.0"
  coverage: any
  dart_style: ^1.0.9+1
  dependency_validator:
    path: ../..
