name: valid
version: 0.0.0
private: true
environment:
  sdk: '>=2.4.0 <3.0.0'
dependencies:
  logging: any
  yaml: any
  fake_project:
    path: ../fake_project
dev_dependencies:
  dependency_validator:
    path: ../..
  pedantic: any
